export const FILTER_BY_EMOTION = "FILTER_BY_EMOTION";
export const FILTER_BY_FACEICON = "FILTER_BY_FACEICON";
export const FILTER_BY_DTW = "FILTER_BY_DTW";
export const ADD_HELPFUL_REVIEW = "ADD_HELPFUL_REVIEW";
export const UPDATE_HELPFUL_REVIEW = "UPDATE_HELPFUL_REVIEW";
export const ADD_HELPFUL_REVIEW_PROPOSE = "ADD_HELPFUL_REVIEW_PROPOSE";
export const UPDATE_HELPFUL_REVIEW_PROPOSE = "UPDATE_HELPFUL_REVIEW_PROPOSE";
